# Site settings
title: A blog about lorem ipsum dolor sit amet
description: A blog about lorem ipsum dolor sit amet
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Lisethe
user_description: In this section I've listed as far as my skillset goes and the things I have gained whilst I was student and placed I worked from simple but crusial Design to tools for my job that I use on the daily basis
user_title: Technology Graduate
email: hello@lisethe.com
twitter_username: lorem_ipsum
github_username: smartLisethe
gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
